name: HGKits
version: '${project.version}'
main: me.isra.hgkits.HGKits
commands:
  kit:
    description: Abre el menú de kits
    usage: /<command>
  start:
    description: Aplica el kit seleccionado al jugador
    usage: /<command>
    permission-message: No tienes permiso para usar este comando.
    default: op
  rank:
    description: Muestra la fama al jugador
    usage: /<command>
