name: HGKits
version: 1.0
main: me.isra.hgkits.HGKits
depend:
  - SlimeWorldManager
  - PlaceholderAPI
  - Vault
  - LCCore
commands:
  team:
    description: Comando para manejar tu equipo
  finalbattle:
    description: Comando que activa la batalla final
    aliases:
      - fb
  kit:
    description: Abre el menú de kits
    usage: /<command>
  start:
    description: Aplica el kit seleccionado al jugador
    usage: /<command>
    permission-message: No tienes permiso para usar este comando.
    default: op
  rank:
    description: Muestra la fama al jugador
    usage: /<command>
  stats:
    description: Show your stats
  top:
    description: Mira los tops disponibles
    usage: /top (kills/deaths/wins/kdr)

permissions:
  chg.default:
    description: Permiso para kits por defecto
    default: true

  chg.vip:
    description: Permiso para kits VIP y anteriores
    default: false
    children:
      chg.default: true

  chg.svip:
    description: Permiso para kits SVIP y anteriores
    default: false
    children:
      chg.vip: true

  chg.elite:
    description: Permiso para kits Elite y anteriores
    default: false
    children:
      chg.svip: true

  chg.optimum:
    description: Permiso para kits Optimum y anteriores
    default: false
    children:
      chg.elite: true
